# nanoplugins.com | nanoplugins.com.br | nanoplugins.fun

#Definições
settings:
  nano-stock-market: false #Caso use o plugin de bolsa(NanoBolsa)
  fortune: true #Uso de fortuna (valor * fortuna)
  actionbar: true #Uso de actionbar
  message: false #Uso de mensagem no chat
  worlds: #Mundos onde funciona
    - "Minas"

#Mensagens
messages:
  #Actionbar ao minerar (Placeholders: %block% & %money% & %bonus% & %fortune% & %stockMarket%)
  actionbar: "&aMinerou um %block% &ae ganhou &7%money% &acoins! &d(%bonus%% | %fortune%)"
  #Mensagem no chat ao minerar (Placeholders: %block% & %money% & %bonus% & %fortune% & %stockMarket%)
  message: "&aMinerou um %block% &ae ganhou &f%money% &acoins! &d(%bonus%% | %fortune%)"

#Blocos
blocks:
  lapis: #Key (coloque o que quiser desde que não repita)
    type: 21 #Id do bloco
    data: 0 #Data do bloco
    name: "&9Minério de Lapis Azul" #Nome para aparecer nas mensagens
    money: 1000.0 #Dinheiro que dá ao minerar
  gold:
    type: 14
    data: 0
    name: "&6Minério de Ouro"
    money: 1000000.0

#Bonus
bonus:
  vip: #Key (coloque o que quiser desde que não repita)
    group: "vip" #Nome do grupo no plugin de permissões
    value: 1.3 #Bonus que é atribuido (100 * 1.3 = 130)
  vipiron:
    group: "vipferro"
    value: 1.4